name: ibp_app_ver2
description: "A new Flutter project."
publish_to: "none" # This line prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.2
  video_player: ^2.4.6
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.1.0
  smooth_page_indicator: ^1.1.0
  firebase_core: ^3.4.1 # Adjusted to a compatible version
  firebase_auth: ^5.2.1 # Adjusted to a compatible version
  cloud_firestore: ^5.4.1 # Adjusted to a compatible version
  provider: ^6.0.0
  image_picker: ^1.1.2
  mime: ^1.0.0
  image: ^3.0.1
  image_picker_for_web: ^3.0.5
  html: ^0.15.0
  universal_html: ^2.0.7
  firebase_storage: ^12.3.0
  http: ^1.2.2
  intl: ^0.19.0
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  cached_network_image: ^3.4.1
  qr_code_scanner: ^1.0.1
  recase: ^4.0.0
  webview_flutter: ^3.0.4
  flutter_tawk: ^0.1.0
  shared_preferences: ^2.0.9
  vector_math: ^2.1.2
  auto_size_text: ^3.0.0
  google_sign_in: ^6.2.1
  device_info_plus: ^9.0.1
  jitsi_meet_wrapper: ^0.2.0+1
  jitsi_meet_flutter_sdk: ^10.2.1
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.4
  firebase_remote_config: ^5.1.3
  firebase_auth_platform_interface: ^7.4.7
  firebase_app_check: ^0.3.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  webview_flutter: ^3.0.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/ibp_logo.png"  # Your custom logo path
flutter:
  uses-material-design: true
  assets:
    - assets/videos/ibp_splash_screen.mp4
    - assets/img/ibp_logo.png
    - assets/img/DefaultUserImage.jpg
    - assets/img/google_logo.png


